backend:
  name: git-gateway
  branch: CMS-Integration
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/horses.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Horses'
            name: 'horses'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Character', name: 'character', widget: 'text' }
